apiVersion: v1
kind: Service
metadata:
  name: campusbuzz-service
spec:
  type: NodePort
  selector:
    app: campusbuzz-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30011
      